1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [8]:
import numpy as np
v = np.zeros(100)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


2.Создать вектор размера 100, заполненный единицами

In [9]:
import numpy as np
v = np.ones(100)
print(v)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


3.Создать вектор размера 100, заполненный числом 3

In [10]:
import numpy as np
v = np.full(100, 3)
print(v)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


4.Как получить документацию о функции numpy.add из командной строки?

In [18]:
import numpy as np
help (np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

5.Поменять 2 строки в матрице 

In [3]:
matrix = [[1,1,1],[2,3,4],[4,5,6],[7,1,2]]
matrix[1], matrix[2] = matrix[2], matrix[1]
matrix

[[1, 1, 1], [4, 5, 6], [2, 3, 4], [7, 1, 2]]

6. Создать вектор со значениями от 10 до 100

In [5]:
import numpy as np
V = np.arange(10,101)
print(V)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


7. Развернуть вектор (первый становится последним)

In [14]:
import numpy as np
V = np.arange(10)
V = V[::-1]
print(V)

[9 8 7 6 5 4 3 2 1 0]


8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [33]:
import numpy as np
Z = np.arange(16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [34]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Создать 3x3 единичную матрицу

In [35]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Создать массив 3x3x3 со случайными значениями

In [36]:
import numpy as np
m = np.random.random((3,3,3))
print(m)

[[[0.63778579 0.25197683 0.96408294]
  [0.440813   0.08095583 0.34958297]
  [0.02535231 0.92042028 0.36987797]]

 [[0.68753291 0.66294509 0.63012794]
  [0.12722113 0.85943856 0.26368007]
  [0.36033063 0.02572591 0.62564368]]

 [[0.80755067 0.26006202 0.96464808]
  [0.36884608 0.11161816 0.72141005]
  [0.20371383 0.94833619 0.98643443]]]


12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [37]:
max_var1, max_var2 = m.min(), m.max()
print(max_var1, max_var2)
print()

0.025352309420815455 0.9864344321245768



13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
import numpy as np
V = np.random.random(30)
m = V.mean()
print(m)

0.542549042929844


14. Создать матрицу с 0 внутри, и 1 на границах

In [39]:
m = np.ones([10,10])
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [41]:
import numpy as np
m = np.diag(np.arange(1, 5), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [42]:
m1 = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
print(m1)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [43]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [44]:
m1 = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
print(m1)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


20. Перемножить матрицы 5x3 и 3x2

In [46]:
a = np.random.random([5,3])
b = np.random.random([3,2])
print(np.dot(a,b))

[[0.21793613 0.22270014]
 [1.23672284 0.95998922]
 [0.35044695 0.38455164]
 [1.17395773 0.89873211]
 [0.79977175 0.6013013 ]]


21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [48]:
m = np.random.randint(low=1, high=25, size=[5,5])
ind = np.where((m > 3) & (m < 8))
m[ind] *=-1
print(m)

[[ 2 20  9 24 19]
 [22 -6 19 12 11]
 [24  1 23 14 18]
 [ 2  1 19 24 16]
 [10  3  1 23  2]]


23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [50]:
m = np.tile(np.arange(5,dtype='float'),[5,1])
print(m.dtype)

float64


24. Есть генератор, сделать с его помощью массив

In [52]:
def generate():
    for x in range(10):
            yield x
        
m = np.fromiter(generate(), dtype='float', count=-1)
print(m)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [53]:
v = np.linspace(start=0, stop=1, num=12)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


26. Отсортировать вектор

In [55]:
v = np.random.random(size=[10])
print(v)
v = np.sort(a=v, axis=0)
print(v)

[0.71089357 0.96369757 0.37204038 0.17366777 0.10875161 0.33677434
 0.56162813 0.24345504 0.08554839 0.27991133]
[0.08554839 0.10875161 0.17366777 0.24345504 0.27991133 0.33677434
 0.37204038 0.56162813 0.71089357 0.96369757]


27. Проверить, одинаковы ли 2 numpy массива

In [57]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(np.array_equal(a,b))

True


28. Сделать массив неизменяемым

In [399]:
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
print(Z)

ValueError: assignment destination is read-only

29. Найти n наибольших значений в массиве

In [329]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9996 9997 9999 9995]


30. Заменить максимальный элемент на ноль

In [68]:
m = np.random.random(10)
m[m.argmax()] = 0
print(m)

[0.         0.66162546 0.69538093 0.62148407 0.8638812  0.29044915
 0.85211442 0.51269927 0.8939092  0.32900115]


31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [69]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [212]:
x = np.arange(8)
y = x + 0.5
a = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(a))

3638.1636371179666


33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [72]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


34. Напечатать все значения в массиве

In [388]:
numpy.arange(100).reshape(25,4).tolist()

[[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27],
 [28, 29, 30, 31],
 [32, 33, 34, 35],
 [36, 37, 38, 39],
 [40, 41, 42, 43],
 [44, 45, 46, 47],
 [48, 49, 50, 51],
 [52, 53, 54, 55],
 [56, 57, 58, 59],
 [60, 61, 62, 63],
 [64, 65, 66, 67],
 [68, 69, 70, 71],
 [72, 73, 74, 75],
 [76, 77, 78, 79],
 [80, 81, 82, 83],
 [84, 85, 86, 87],
 [88, 89, 90, 91],
 [92, 93, 94, 95],
 [96, 97, 98, 99]]

35. Найти ближайшее к заданному значению число в заданном массиве

In [173]:
Z = np.arange(15)
v = np.random.uniform(0,15)
index = (np.abs(Z-v)).argmin()
print(Z[index])

13


36. Преобразовать массив из float в int

In [362]:
import numpy as np
x = np.arange(10, dtype='int32')
y = x.view('float32')
y[:] = x

print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


37. Каков эквивалент функции enumerate для numpy массивов?

In [89]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


38. Случайно расположить p элементов в 2D массив

In [93]:
n = 10
p = 3
a = np.zeros((n,n), int)
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


39. Отнять среднее из каждой строки в матрице

In [146]:
a = np.random.randint(0,10,(2,2))
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[3 8]
 [9 9]]
[[-2.5  2.5]
 [ 0.   0. ]]


40. Отсортировать матрицу по n-ому столбцу

In [95]:
a = np.random.randint(0,10,(3,3))
n = 1
print(a)
print(a[a[:,n].argsort()])

[[3 7 5]
 [6 2 1]
 [1 1 0]]
[[1 1 0]
 [6 2 1]
 [3 7 5]]


41. Определить, есть ли в 2D массиве нулевые столбцы

In [304]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [282]:
m = np.ones(10)
i = np.random.randint(0,len(m),20)
m += np.bincount(i, minlength=len(m))
print(m)

[4. 3. 3. 2. 2. 3. 1. 3. 5. 4.]


43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [130]:
w,h = 10,10
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [400]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[46 58 66 57]
 [46 40 49 40]
 [64 59 46 60]]
